#!/usr/bin/env python3
"""
analyze_trading.py - Core trading analysis using GitHub Copilot AI models.

Reads forex_data.csv, builds a structured prompt, calls the GitHub Copilot
chat completions API (OpenAI-compatible), and writes a JSON result file.

Usage:
    python scripts/analyze_trading.py \
        --csv forex_data.csv \
        --output analysis_result.json \
        --model claude-opus-4-5 \
        --verify-model claude-sonnet-4-5
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone

import pandas as pd
import requests

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
COPILOT_API_URL = "https://api.githubcopilot.com/chat/completions"
MAX_CANDLES_IN_PROMPT = 50  # keep prompt size manageable


# ---------------------------------------------------------------------------
# CSV Parsing
# ---------------------------------------------------------------------------

def parse_csv(csv_path: str) -> dict:
    """Parse the forex_data.csv sections into a structured dict."""
    with open(csv_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    data = {
        "metadata": {},
        "pair_info": {},
        "active_positions": [],
        "pending_orders": [],
        "closed_deals": [],
        "m5_candles": [],
        "m15_candles": [],
        "h1_candles": [],
    }

    section = None
    headers = []

    for line in lines:
        line = line.rstrip("\n")

        # --- Section detection ---
        if line.startswith("# MARKET DATA ANALYSIS"):
            data["metadata"]["report_time"] = line.split(" - ")[-1].strip()
            continue
        if line.startswith("# Generated by"):
            data["metadata"]["generator"] = line.replace("# Generated by ", "").strip()
            continue
        if line.startswith("# Symbol:"):
            data["metadata"]["symbol"] = line.split(":")[1].strip()
            continue
        if line.startswith("# Last Successful Update:"):
            data["metadata"]["last_update"] = line.split(":", 1)[1].strip()
            continue
        if "# PAIR INFORMATION" in line:
            section = "pair_info"
            headers = []
            continue
        if "# ACTIVE POSITIONS" in line:
            section = "active_positions"
            headers = []
            continue
        if "# PENDING ORDERS" in line:
            section = "pending_orders"
            headers = []
            continue
        if "# LAST 5 CLOSED DEALS" in line:
            section = "closed_deals"
            headers = []
            continue
        if "# M5 CANDLES" in line:
            section = "m5_candles"
            headers = []
            continue
        if "# M15 CANDLES" in line:
            section = "m15_candles"
            headers = []
            continue
        if "# H1 CANDLES" in line:
            section = "h1_candles"
            headers = []
            continue
        if line.startswith("# "):
            continue  # skip other comment lines

        if not line.strip() or line.strip() == "":
            continue

        # --- Data rows ---
        parts = [p.strip() for p in line.split(",")]

        if section == "pair_info":
            if len(parts) >= 2:
                data["pair_info"][parts[0]] = parts[1]
            continue

        if section in ("active_positions", "pending_orders", "closed_deals",
                       "m5_candles", "m15_candles", "h1_candles"):
            if not headers:
                # Deduplicate headers by appending _2, _3 for repeats
                seen: dict = {}
                deduped = []
                for h in parts:
                    if h in seen:
                        seen[h] += 1
                        deduped.append(f"{h}_{seen[h]}")
                    else:
                        seen[h] = 1
                        deduped.append(h)
                headers = deduped
                continue
            row = dict(zip(headers, parts))
            data[section].append(row)

    return data


# ---------------------------------------------------------------------------
# Prompt builder
# ---------------------------------------------------------------------------

def build_analysis_prompt(data: dict) -> str:
    """Build a detailed analysis prompt from parsed CSV data."""
    symbol = data["metadata"].get("symbol", "XAUUSD")
    report_time = data["metadata"].get("report_time", "Unknown")
    pair_info = data["pair_info"]

    bid = pair_info.get("Current Bid", "N/A")
    ask = pair_info.get("Current Ask", "N/A")

    # Active positions
    active = data["active_positions"]
    active_text = "No active positions." if not active else "\n".join(
        f"  - Ticket {p.get('Ticket','?')}: {p.get('Type','?')} {p.get('Volume','?')} lots @ {p.get('Price','?')}, SL={p.get('S/L','?')}, TP={p.get('T/P','?')}"
        for p in active
    )

    # Closed deals
    deals = data["closed_deals"]
    deals_text = "No closed deals." if not deals else "\n".join(
        f"  - [{d.get('Time','?')}] {d.get('Type','?')} {d.get('Volume','?')} lots"
        f" open @ {d.get('Price','?')}, close @ {d.get('Price_2','?')}, Profit={d.get('Profit','?')}"
        for d in deals
    )

    # Candle summaries (last N candles only to stay within token budget)
    def candle_rows(candles, limit=MAX_CANDLES_IN_PROMPT):
        recent = candles[:limit]
        rows = ["Time,Dir,Open,High,Low,Close,Volume"] + [
            f"{c.get('Time','?')},{c.get('Direction','?')},{c.get('Open','?')},{c.get('High','?')},{c.get('Low','?')},{c.get('Close','?')},{c.get('Volume','?')}"
            for c in recent
        ]
        return "\n".join(rows)

    m5_text = candle_rows(data["m5_candles"])
    m15_text = candle_rows(data["m15_candles"])
    h1_text = candle_rows(data["h1_candles"])

    prompt = f"""You are an expert forex and commodities trading analyst specializing in XAUUSD (Gold/USD).
Analyze the following live trading data and produce a comprehensive structured analysis.

## Market Snapshot
- Symbol: {symbol}
- Report Time: {report_time}
- Current Bid: {bid}
- Current Ask: {ask}

## Active Positions
{active_text}

## Last 5 Closed Deals (most recent first)
{deals_text}

## M5 Candles (last {MAX_CANDLES_IN_PROMPT} bars, most recent first)
{m5_text}

## M15 Candles (last {MAX_CANDLES_IN_PROMPT} bars, most recent first)
{m15_text}

## H1 Candles (last {MAX_CANDLES_IN_PROMPT} bars, most recent first)
{h1_text}

---

## Analysis Requirements

Provide your analysis in the following JSON format (no additional text outside the JSON block):

```json
{{
  "analysis_timestamp": "<ISO 8601 UTC timestamp>",
  "symbol": "{symbol}",
  "current_price": {{
    "bid": <number>,
    "ask": <number>,
    "spread_pips": <number>
  }},
  "performance_summary": {{
    "closed_deals_count": <integer>,
    "winning_trades": <integer>,
    "losing_trades": <integer>,
    "win_rate_pct": <number>,
    "total_profit": <number>,
    "avg_profit_per_trade": <number>,
    "best_trade_profit": <number>,
    "worst_trade_profit": <number>,
    "commentary": "<2-3 sentence summary>"
  }},
  "risk_assessment": {{
    "active_positions_count": <integer>,
    "total_exposure_lots": <number>,
    "risk_level": "<LOW|MEDIUM|HIGH|CRITICAL>",
    "open_pnl": <number>,
    "risk_warnings": ["<warning>"],
    "commentary": "<2-3 sentence assessment>"
  }},
  "technical_analysis": {{
    "m5": {{
      "trend": "<BULLISH|BEARISH|SIDEWAYS>",
      "strength": <0-100>,
      "key_levels": {{"support": <number>, "resistance": <number>}},
      "last_close": <number>,
      "signals": ["<signal>"],
      "commentary": "<brief>"
    }},
    "m15": {{
      "trend": "<BULLISH|BEARISH|SIDEWAYS>",
      "strength": <0-100>,
      "key_levels": {{"support": <number>, "resistance": <number>}},
      "last_close": <number>,
      "signals": ["<signal>"],
      "commentary": "<brief>"
    }},
    "h1": {{
      "trend": "<BULLISH|BEARISH|SIDEWAYS>",
      "strength": <0-100>,
      "key_levels": {{"support": <number>, "resistance": <number>}},
      "last_close": <number>,
      "signals": ["<signal>"],
      "commentary": "<brief>"
    }}
  }},
  "trading_signals": [
    {{
      "timeframe": "<M5|M15|H1>",
      "type": "<BUY|SELL|HOLD>",
      "entry_price": <number>,
      "stop_loss": <number>,
      "take_profit": <number>,
      "risk_reward_ratio": <number>,
      "confidence_pct": <0-100>,
      "reason": "<explanation>"
    }}
  ],
  "final_recommendation": {{
    "action": "<BUY|SELL|HOLD>",
    "confidence_pct": <0-100>,
    "entry_price": <number>,
    "stop_loss": <number>,
    "take_profit": <number>,
    "risk_reward_ratio": <number>,
    "position_size_suggestion": "<e.g., 0.01-0.05 lots for conservative risk>",
    "time_horizon": "<e.g., 1-4 hours>",
    "reasoning": "<3-5 sentence detailed reasoning>",
    "key_risks": ["<risk>"],
    "invalidation_level": <number>
  }},
  "market_context": {{
    "volatility": "<LOW|MEDIUM|HIGH>",
    "session": "<ASIAN|LONDON|NEW_YORK|OVERLAP>",
    "market_sentiment": "<BULLISH|BEARISH|NEUTRAL>",
    "commentary": "<2-3 sentences on broader context>"
  }}
}}
```

Respond ONLY with the JSON block above. No preamble, no explanation outside the JSON.
"""
    return prompt


# ---------------------------------------------------------------------------
# Copilot API call
# ---------------------------------------------------------------------------

def call_copilot_api(prompt: str, model: str, token: str, max_retries: int = 3) -> str:
    """Call GitHub Copilot chat completions API and return the raw response text."""
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
        "Copilot-Integration-Id": "github-copilot-trading-analysis",
        "Editor-Version": "vscode/1.90.0",
        "Editor-Plugin-Version": "copilot-chat/0.16.0",
    }
    payload = {
        "model": model,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are an expert trading analyst. You always respond with valid JSON only, "
                    "exactly as instructed. No markdown fences, no additional commentary."
                ),
            },
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.1,
        "max_tokens": 4096,
        "top_p": 0.95,
    }

    for attempt in range(1, max_retries + 1):
        try:
            response = requests.post(
                COPILOT_API_URL, headers=headers, json=payload, timeout=120
            )
            if response.status_code == 200:
                data = response.json()
                return data["choices"][0]["message"]["content"].strip()
            elif response.status_code == 429:
                wait = 2 ** attempt
                print(f"[WARN] Rate limited (attempt {attempt}). Waiting {wait}s...")
                time.sleep(wait)
            else:
                print(f"[ERROR] API error {response.status_code}: {response.text[:500]}")
                if attempt == max_retries:
                    raise RuntimeError(
                        f"Copilot API returned {response.status_code}: {response.text[:200]}"
                    )
                time.sleep(2)
        except requests.exceptions.Timeout:
            print(f"[WARN] Request timed out (attempt {attempt})")
            if attempt == max_retries:
                raise

    raise RuntimeError("All API attempts failed")


def extract_json_from_response(raw: str) -> dict:
    """Extract and parse JSON from model response (handles markdown fences)."""
    text = raw.strip()
    # Strip markdown code fences if present
    if text.startswith("```"):
        lines = text.split("\n")
        # Remove first line (```json or ```) and last line (```)
        inner = "\n".join(lines[1:])
        if inner.rstrip().endswith("```"):
            inner = "\n".join(inner.rstrip().split("\n")[:-1])
        text = inner.strip()
    return json.loads(text)


# ---------------------------------------------------------------------------
# Verification pass
# ---------------------------------------------------------------------------

def verify_analysis(primary_result: dict, data: dict, model: str, token: str) -> dict:
    """Run a second lighter verification pass with a different model."""
    summary_prompt = f"""You are a second-opinion trading analyst.
Review this primary analysis and verify or adjust the final recommendation.

Primary analysis summary:
- Symbol: {primary_result.get('symbol')}
- Final recommendation: {json.dumps(primary_result.get('final_recommendation', {}), indent=2)}
- Technical signals detected: {json.dumps([s.get('type') for s in primary_result.get('trading_signals', [])], indent=2)}
- Market context: {json.dumps(primary_result.get('market_context', {}), indent=2)}

Active positions: {len(data.get('active_positions', []))}
Recent candle trend M15: {data['m15_candles'][0].get('Direction','?') if data['m15_candles'] else 'N/A'}

Respond ONLY with a JSON object in this exact format:
{{
  "verified": <true|false>,
  "agreement_level": "<AGREE|PARTIAL|DISAGREE>",
  "adjusted_action": "<BUY|SELL|HOLD>",
  "adjusted_confidence_pct": <0-100>,
  "notes": "<1-2 sentences on any adjustments or confirmations>"
}}
"""
    raw = call_copilot_api(summary_prompt, model, token)
    return extract_json_from_response(raw)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Analyze forex trading data with Copilot AI")
    parser.add_argument("--csv", required=True, help="Path to forex_data.csv")
    parser.add_argument("--output", required=True, help="Path to output JSON file")
    parser.add_argument("--model", default="claude-opus-4-5", help="Primary analysis model")
    parser.add_argument("--verify-model", default="claude-sonnet-4-5", help="Verification model")
    args = parser.parse_args()

    token = os.environ.get("COPILOT_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if not token:
        print("[ERROR] COPILOT_TOKEN or GITHUB_TOKEN environment variable is required")
        sys.exit(1)

    print(f"[INFO] Parsing {args.csv}...")
    data = parse_csv(args.csv)
    print(f"[INFO] Parsed: {len(data['m5_candles'])} M5, {len(data['m15_candles'])} M15, {len(data['h1_candles'])} H1 candles")
    print(f"[INFO] Active positions: {len(data['active_positions'])}, Closed deals: {len(data['closed_deals'])}")

    print(f"[INFO] Running primary analysis with model: {args.model}")
    prompt = build_analysis_prompt(data)
    raw_response = call_copilot_api(prompt, args.model, token)

    print("[INFO] Parsing primary analysis response...")
    result = extract_json_from_response(raw_response)
    result["primary_model"] = args.model
    result["analysis_timestamp"] = datetime.now(timezone.utc).isoformat()

    print(f"[INFO] Running verification with model: {args.verify_model}")
    try:
        verification = verify_analysis(result, data, args.verify_model, token)
        result["verification"] = verification
        result["verification_model"] = args.verify_model
        print(f"[INFO] Verification: {verification.get('agreement_level')} - {verification.get('notes')}")
    except Exception as exc:
        print(f"[WARN] Verification step failed (non-fatal): {exc}")
        result["verification"] = {"verified": False, "notes": str(exc)}

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    print(f"[INFO] Analysis written to {args.output}")

    # Print summary to stdout for workflow logs
    rec = result.get("final_recommendation", {})
    print("\n" + "=" * 60)
    print(f"  RECOMMENDATION : {rec.get('action','?')}")
    print(f"  CONFIDENCE     : {rec.get('confidence_pct','?')}%")
    print(f"  ENTRY PRICE    : {rec.get('entry_price','?')}")
    print(f"  STOP LOSS      : {rec.get('stop_loss','?')}")
    print(f"  TAKE PROFIT    : {rec.get('take_profit','?')}")
    print(f"  R/R RATIO      : {rec.get('risk_reward_ratio','?')}")
    print("=" * 60)


if __name__ == "__main__":
    main()
